apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: exchange-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
      - watch
