apiVersion: v1
kind: Service
metadata:
  name: exchange-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: exchange
  type: LoadBalancer
