apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exchange-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: exchange
    spec:
      serviceAccountName: exchange-service-account
      containers:
        - name: exchange
          image: exchange:release
          ports:
            - containerPort: 4000
          args: ["foreground"]
          env:
            - name: PORT
              value: "4000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

